#!/usr/bin/env python3
"""
📊 FBI Daily Briefing — Token Usage, System Health & Opportunities
Uses Telegram rich formatting: headings, tables, checklists, collapsible sections.
"""

import sys, os, json, re
sys.path.insert(0, '/root/projects/table-artist')
from table_artist import unicode_table as ut
import sqlite3
import subprocess
from datetime import datetime, timezone

HOME = os.path.expanduser("~")
HERMES_DIR = os.path.join(HOME, ".hermes")
STATE_DB = os.path.join(HERMES_DIR, "state.db")
ERROR_LOG = os.path.join(HERMES_DIR, "logs", "errors.log")
WIB = datetime.now().strftime("%Y-%m-%d %H:%M WIB")


def run(cmd):
    try:
        r = subprocess.run(cmd, shell=True, capture_output=True, text=True, timeout=15)
        return r.stdout.strip()
    except:
        return ""


def get_tokens():
    if not os.path.exists(STATE_DB):
        return None
    try:
        conn = sqlite3.connect(STATE_DB)
        today_start = datetime.now(timezone.utc).replace(hour=0, minute=0, second=0, microsecond=0).timestamp()
        cutoff = today_start - 86400

        rows = conn.execute("""
            SELECT
                COUNT(*),
                COALESCE(SUM(input_tokens), 0),
                COALESCE(SUM(output_tokens), 0),
                COALESCE(SUM(estimated_cost_usd), 0),
                COALESCE(SUM(message_count), 0)
            FROM sessions WHERE started_at > ?
        """, (cutoff,)).fetchone()

        today = conn.execute("""
            SELECT
                COUNT(*),
                COALESCE(SUM(input_tokens), 0),
                COALESCE(SUM(output_tokens), 0),
                COALESCE(SUM(estimated_cost_usd), 0)
            FROM sessions WHERE started_at > ?
        """, (today_start,)).fetchone()

        conn.close()

        if rows[0] > 0:
            total_in = rows[1] + today[1]
            total_out = rows[2] + today[2]
            return {
                "sessions": rows[0],
                "messages": rows[4],
                "input": rows[1],
                "output": rows[2],
                "total": rows[1] + rows[2],
                "cost": rows[3],
                "today_sessions": today[0],
                "today_input": today[1],
                "today_output": today[2],
                "today_total": today[1] + today[2],
                "today_cost": today[3],
            }
        return None
    except Exception as e:
        return {"error": str(e)}


def get_sysinfo():
    """Grab live system stats."""
    uptime = run("uptime -p").replace("up ", "")
    ram = run("free -h | awk '/Mem:/ {print $3\"/\"$2}'")
    disk = run("df -h / | awk 'NR==2 {print $5\", \"$4\" free\"}'")
    swap = run("swapon --show | awk 'NR>1 {print $3}'")
    load = run("cat /proc/loadavg | awk '{print $1\", \"$2\", \"$3}'")
    return {"uptime": uptime, "ram": ram, "disk": disk, "swap": swap or "0", "load": load}


def get_errors():
    """
    Get structured errors from the new BREACH Error Log system.
    Falls back to old Hermes errors.log if structured log is empty.
    """
    NEW_ERROR_LOG = os.path.expanduser("~/.hermes/scripts/.error_log.json")
    SUMMARY_CACHE = "/root/projects/bounty-output/error_summary_report.txt"
    if not os.path.exists(SUMMARY_CACHE):
        SUMMARY_CACHE = os.path.expanduser("~/.hermes/cron/output/error_summary_report.txt")

    # Priority 1: Use cached error summary report (generated by error_summary cron)
    if os.path.exists(SUMMARY_CACHE):
        try:
            with open(SUMMARY_CACHE) as f:
                content = f.read().strip()
            if content and "Bersih" not in content and "tidak ada error" not in content:
                return [content]  # Return the full summary
        except (OSError, IOError):
            pass

    # Priority 2: Read from structured error log directly
    if os.path.exists(NEW_ERROR_LOG):
        try:
            with open(NEW_ERROR_LOG) as f:
                entries = json.load(f)
            if not entries:
                return []

            # Group: CRITICAL and ERROR only (skip WARNING/INFO for daily briefing)
            bad = [e for e in entries if e["level"] in ("CRITICAL", "ERROR")][-5:]

            if not bad:
                return []

            result = []
            for e in bad:
                detail = e["detail"][:120]
                rec = e.get("recommendation", "")
                if e["level"] == "CRITICAL":
                    text = f"💀 [{e['script']}] {detail}"
                else:
                    text = f"🔴 [{e['script']}] {detail}"
                if rec:
                    text += f" — 💡 {rec[:80]}"
                result.append(text)
            return result
        except (json.JSONDecodeError, OSError):
            pass

    # Priority 3: Fallback to old Hermes errors.log
    if os.path.exists(ERROR_LOG):
        try:
            r = subprocess.run(
                f"tail -100 {ERROR_LOG} | grep -iE '\\\\b(ERROR|CRITICAL|FAILED|Traceback|Exception)\\\\b'",
                shell=True, capture_output=True, text=True, timeout=10
            )
            lines = [l.strip() for l in r.stdout.split("\\n") if l.strip()]
            translated = []
            for line in lines[-5:]:
                translated.append(_translate_error(line))
            return translated
        except Exception:
            return []

    return []


def _translate_error(raw):
    raw_lower = raw.lower()
    if "tool" in raw_lower and ("returned" in raw_lower or "error" in raw_lower):
        tool_name = "proses"
        if "read_file" in raw: tool_name = "baca file"
        elif "write_file" in raw: tool_name = "nulis file"
        elif "cron" in raw_lower: tool_name = "jadwal tugas"
        elif "terminal" in raw: tool_name = "jalanin perintah"
        elif "patch" in raw: tool_name = "edit file"
        elif "search" in raw_lower: tool_name = "cari data"
        elif "send" in raw_lower: tool_name = "kirim pesan"
        return f"❌ Gagal {tool_name}, coba ulang nanti"
    if "connection" in raw_lower or "timeout" in raw_lower or "network" in raw_lower:
        return "🌐 Gagal konek ke server, cek internet"
    if "memory" in raw_lower or "oom" in raw_lower:
        return "💥 RAM abis! Proses terpaksa dimatiin"
    if "disk" in raw_lower or "space" in raw_lower or "no space" in raw_lower:
        return "💾 Storage penuh!"
    if "permission" in raw_lower or "denied" in raw_lower or "forbidden" in raw_lower:
        return "🔒 Ga punya akses, perlu izin lebih"
    if "not found" in raw_lower or "no such" in raw_lower:
        return "🔍 File atau folder ga ditemukan"
    if "rate" in raw_lower and "limit" in raw_lower:
        return "⏳ Kecepatan limit, tunggu sebentar"
    if "auth" in raw_lower or "unauthorized" in raw_lower or "token" in raw_lower:
        return "🔑 Token/login bermasalah, perlu login ulang"
    return f"⚠️ `{raw[:80]}...`"


def fmt(n):
    if n >= 1_000_000: return f"{n/1_000_000:.1f}jt"
    elif n >= 1_000: return f"{n/1_000:.1f}k"
    return str(n)


def main():
    lines = []
    lines.append(f"📊 Daily Briefing — grace-ku-sayang")
    lines.append(f"`{WIB} `")
    lines.append("")

    # ── System Health ──
    sys = get_sysinfo()
    lines.append("🖥️ Sistem")
    lines.append("```")
    raw = ut([
        {"Metric": "Uptime", "Value": sys['uptime']},
        {"Metric": "RAM", "Value": sys['ram']},
        {"Metric": "Swap", "Value": f"{sys['swap']} used"},
        {"Metric": "Disk", "Value": sys['disk']},
        {"Metric": "Load", "Value": sys['load']},
    ], "")
    # Strip backtick wrapping since we're inside a code block
    for line in raw.split("\n"):
        s = line.strip()
        if s.startswith("`") and s.endswith("`"):
            lines.append(s[1:-1])
        else:
            lines.append(s)
    lines.append("```")
    lines.append("")

    # ── Token Usage ──
    lines.append("💎 Pemakaian Token (24 jam)")
    lines.append("```")
    t = get_tokens()
    if t and "error" not in t:
        token_rows = [
            {"Metric": "Sessions", "Value": str(t['sessions'])},
            {"Metric": "Messages", "Value": str(t['messages'])},
            {"Metric": "Input", "Value": f"{fmt(t['input'])} tok"},
            {"Metric": "Output", "Value": f"{fmt(t['output'])} tok"},
            {"Metric": "Total", "Value": f"{fmt(t['total'])} tok"},
            {"Metric": "Cost", "Value": f"${t['cost']:.6f}"},
        ]
        if t['today_sessions'] > 0:
            token_rows.append({"Metric": "Today", "Value": f"{t['today_sessions']} ses · {fmt(t['today_total'])} tok · ${t['today_cost']:.6f}"})
        raw = ut(token_rows, "")
        for line in raw.split("\n"):
            s = line.strip()
            if s.startswith("`") and s.endswith("`"):
                lines.append(s[1:-1])
            else:
                lines.append(s)
    else:
        lines.append("📭 Belum ada aktivitas hari ini")
    lines.append("```")
    lines.append("")

    # ── Daily Checklist ──
    lines.append("✅ Cek Harian")
    lines.append("- [x] Hermes gateway nyala")
    lines.append(f"- [x] Disk normal ({sys['disk'].split(',')[0].strip()} used)")
    lines.append(f"- [x] RAM normal ({sys['ram']})")
    lines.append("- [x] Swap aktif")
    lines.append("- [ ] Income pipeline dicek")
    lines.append("- [ ] Proxy pool dites")
    lines.append("- [ ] Airdrop monitor dicek")
    lines.append("")

    # ── Error Log ──
    err_content = None
    SUMMARY_CACHE = "/root/projects/bounty-output/error_summary_report.txt"
    if not os.path.exists(SUMMARY_CACHE):
        SUMMARY_CACHE = os.path.expanduser("~/.hermes/cron/output/error_summary_report.txt")

    # Priority 1: pakai cache dari error_summary cron
    if os.path.exists(SUMMARY_CACHE):
        try:
            with open(SUMMARY_CACHE) as f:
                content = f.read().strip()
            if content and "Bersih" not in content and "bersih" not in content:
                err_content = content
        except (OSError, IOError):
            pass

    # Priority 2: langsung baca dari error log
    if not err_content:
        from lib.error_log import ErrorLog as EL
        err_content = EL.format_summary()

    if err_content:
        lines.append("⚠️ **Error Log**")
        lines.append(err_content)
    else:
        lines.append("✅ Error Log — bersih, semua normal")
    lines.append("")

    # ── Income Pipeline Summary ──
    inc_cache = "/root/projects/bounty-output/pipeline_report.txt"
    if os.path.exists(inc_cache):
        try:
            with open(inc_cache) as f:
                inc_content = f.read()
            sl_count = inc_content.count("[slavelabour]")
            fl_count = inc_content.count("[Freelancer]")
            total = sl_count + fl_count
            lines.append("💰 Income Scan")
            lines.append("```")
            if total > 0:
                raw = ut([
                    {"Sumber": "Reddit Gigs", "Jumlah": str(sl_count)},
                    {"Sumber": "Freelancer", "Jumlah": str(fl_count)},
                ], "")
                for line in raw.split("\n"):
                    s = line.strip()
                    if s.startswith("`") and s.endswith("`"):
                        lines.append(s[1:-1])
                    else:
                        lines.append(s)
                high_val = re.findall(r'\$[5-9]\d{2,}|\$\d{4,}', inc_content)
                if high_val:
                    lines.append(f"High-value gigs: {len(high_val)}")
            else:
                lines.append("📭 Belum ada gig baru")
            lines.append("```")
            lines.append("")
        except Exception:
            pass

    # ── Opportunities ──
    lines.append("🎯 Peluang Hari Ini")
    lines.append("")
    lines.append("**Testnet Faucets:**")
    lines.append("```")
    raw = ut([
        {"Chain": "Sepolia ETH", "Faucet": "faucet.sepolia.dev"},
        {"Chain": "zkSync Sepolia", "Faucet": "portal.zksync.io/faucet"},
        {"Chain": "Scroll Sepolia", "Faucet": "scroll.io/faucet"},
        {"Chain": "Base Sepolia", "Faucet": "base.org/faucet"},
        {"Chain": "Polygon Amoy", "Faucet": "faucet.polygon.technology"},
    ], "")
    for line in raw.split("\n"):
        s = line.strip()
        if s.startswith("`") and s.endswith("`"):
            lines.append(s[1:-1])
        else:
            lines.append(s)
    lines.append("```")
    lines.append("")
    lines.append("**Active Airdrops:**")
    lines.append("1. Hypernova — Prop Firm, up to $200k [Arbitrum]")
    lines.append("2. Interstate — Trading Terminal, genesis [Solana]")
    lines.append("3. DeepBook — Liquidity Layer, check eligibility [Sui]")
    lines.append("4. ArcNova AI — AI Cinematic, earn $ROAM [BNB Chain]")
    lines.append("5. Roam — Telecom DePIN, earn $ROAM [Solana]")
    lines.append("")

    # ── Footer ──
    lines.append("---")
    lines.append("🔥 BREACH — grace-ku-sayang")

    print("\n".join(lines))


if __name__ == "__main__":
    main()
